<?php
return [
    'roles' => [
        'ADMIN' => 'Admin',
        'STUDENT' => 'Student',
        'PARENT' => 'Parent',
        'TUTOR' => 'Tutor',
        'SCHOOL' => 'School'
    ],
    'statuses' => [
        'PENDING' => 1,
        'APPROVED' => 2,
        'REJECTED' => 3,
    ],
    'subjects' => [
        'ENGLISH' => 'English',
        'MATH' => 'Math',
        'VERBAL_NON_VERBAL_REASONING' => 'Verbal & Non-Verbal Reasoning',
    ],
    'locations' => [
        'EALING' => 'Ealing',
        'KINGSTON' => 'Kingston',
        'NEW_MALDEN' => 'New Malden',
        'SLOUGH' => 'Slough',
        'WIMBLEDON' => 'Wimbledon',
        'SUTTON' => 'Sutton',
        'ONLINE' => 'online',
    ],
    'mode' => [
        'IN_PERSON' => 'in person',
        'ONLINE' => 'online',
    ],
    'course_type' => [
        'WEEKLY' => 1,
        'DAILY' => 2,
        'MONTHLY' => 3
    ],
    'acdemic_start_year' => [
        2025,
        2026,
        2027,
        2028,
    ],
    'acdemic_end_year' => [
        2026,
        2027,
        2028,
        2029,
    ],
    'completed' => [
        'YES' => 1,
        'NO' => 0,
    ],
    'completed_reverse' => [
        1 => "YES",
        0 => "NO",
    ],
    'path' => [
        'image' => 1,
        'video' => 2,
        'pdf' => 3,
        'others' => 4,
    ],
    'modes' => [
        'in_person' => 'In person',
        'online' => 'Online',
    ],
    'months' => [
        'January',
        'February',
        'March',
        'April',
        'May',
        'June',
        'July',
        'August',
        'September',
        'October',
        'November',
        'December',
    ],
    'regions' => [
        // United Kingdom Regions
        ['name' => 'Berkshire', 'country_code' => 'GB'],
        ['name' => 'Bexley and Bromley', 'country_code' => 'GB'],
        ['name' => 'Birmingham, Walsall, Wolverhamption and Wrekin (West Midlands)', 'country_code' => 'GB'],
        ['name' => 'Buckinghamshire', 'country_code' => 'GB'],
        ['name' => 'Devon', 'country_code' => 'GB'],
        ['name' => 'Dorset', 'country_code' => 'GB'],
        ['name' => 'Essex', 'country_code' => 'GB'],
        ['name' => 'Essex-Redbridge', 'country_code' => 'GB'],
        ['name' => 'Gloucestershire', 'country_code' => 'GB'],
        ['name' => 'Hertfordshire (Other and North London)', 'country_code' => 'GB'],
        ['name' => 'Hertfordshire (South West)', 'country_code' => 'GB'],
        ['name' => 'Kent', 'country_code' => 'GB'],
        ['name' => 'Lancashire & Cumbria', 'country_code' => 'GB'],
        ['name' => 'Lincolnshire', 'country_code' => 'GB'],
        ['name' => 'Medway', 'country_code' => 'GB'],
        ['name' => 'Northern Ireland', 'country_code' => 'GB'],
        ['name' => 'Surrey (Sutton, Kingston and Wandsworth)', 'country_code' => 'GB'],
        ['name' => 'Trafford', 'country_code' => 'GB'],
        ['name' => 'Warwickshire', 'country_code' => 'GB'],
        ['name' => 'Wiltshire', 'country_code' => 'GB'],
        ['name' => 'Wirral', 'country_code' => 'GB'],
        ['name' => 'Yorkshire', 'country_code' => 'GB'],
        // Dubai Regions
        ['name' => 'Dubai', 'country_code' => 'DU'],
        ['name' => 'Abu Dhabi', 'country_code' => 'DU'],
        ['name' => 'Sharjah', 'country_code' => 'DU'],
        ['name' => 'Ajman', 'country_code' => 'DU'],
        ['name' => 'Ras Al Khaimah', 'country_code' => 'DU'],
        ['name' => 'Fujairah', 'country_code' => 'DU'],
        ['name' => 'Umm Al Quwain', 'country_code' => 'DU'],
    ],
    'genders' => [
        'male',
        'female',
        'Prefer not to say'
    ],
    'target_schools' => [
        'Both',
        'Grammer',
        'Independent',
    ],
    'assignment_content' => [
        'TopicContent' => 'App\Models\CourseTopic',
        'SubTopicContent' => 'App\Models\CourseSubTopic',
        'TopicTest' => 'App\Models\CourseTopicTest',
        'SubTopicTest' => 'App\Models\CourseSubTopicTest'
    ],
    'product_types' => [
        'course' => 1,
        'mock' => 2,
        'mock_exam' => 2, // Alias for mock
        'paper' => 3,
        'papers' => 3,
        'extracted_paper' => 3, // Alias for papers
    ],
    'table_map' => [
        'course' => 'courses',
        'mock' => 'mock_exams',
        'mock_exam' => 'mock_exams',
        'papers' => 'papers',
        'extracted_paper' => 'papers',
    ],
    'week_days' => [1 => 'Monday', 2 => 'Tuesday', 3 => 'Wednesday', 4 => 'Thursday', 5 => 'Friday', 6 => 'Saturday', 7 => 'Sunday'],
    'gap_between_start_end_time' => 29,
    'billing_cycle' => [
        ['period' => 1, 'name' => 'MONTHLY'],
        ['period' => 3, 'name' => '3 MONTHS'],
        ['period' => 6, 'name' => '6 MONTHS'],
        ['period' => 12, 'name' => '12 MONTHS'],
    ],
    'currency' => [
        '€' => 'eur',
        '$' => 'usd',
        '£' => 'gbp',
    ],
    'dummy_image' => 'https://images.pexels.com/photos/674010/pexels-photo-674010.jpeg',
    'stripe_secret' => env('STRIPE_SECRET', 'sk_test_51RrEFZPBXobf6dxwdjRjXCHBGGcyMM5JvqdUH6l1MYZy5VUTRlpTlrRb0heiJI3PpTD5ImfAfa4u70sPb8bFnscO00LdIM35CN'),
    'stripe_key' => env('STRIPE_KEY', 'pk_test_51RrEFZPBXobf6dxwTZVQSWHkX98T1NHdzInmjT7XX8txPyp2wMEwIBmBk8VNFr6m4bZd7nSMiH2mkKFdhjq3phKL00F1xm10lM'),
    'default_password_for_school' => 12345678,
    'schools' => [
        ['name' => "Aylesbury Grammar School", 'country_code' => 'GB'],
        ['name' => "Aylesbury High School", 'country_code' => 'GB'],
        ['name' => "Beaconsfield High School", 'country_code' => 'GB'],
        ['name' => "Burnham Grammar School", 'country_code' => 'GB'],
        ['name' => "Chesham Grammar School", 'country_code' => 'GB'],
        ['name' => "Dame Alice Queen's", 'country_code' => 'GB'],
        ['name' => "Dr Challoner's Grammar School (Boys)", 'country_code' => 'GB'],
        ['name' => "Dr Challoner's High School (Girls)", 'country_code' => 'GB'],
        ['name' => "Greenshaw High School", 'country_code' => 'GB'],
        ['name' => "Herschel Grammar School", 'country_code' => 'GB'],
        ['name' => "John Hampden Grammar", 'country_code' => 'GB'],
        ['name' => "Kendrick School", 'country_code' => 'GB'],
        ['name' => "The Latymer School", 'country_code' => 'GB'],
        ['name' => "Langley Grammar School", 'country_code' => 'GB'],
        ['name' => "Nonsuch High School for Girls", 'country_code' => 'GB'],
        ['name' => "Queen Elizabeth's School", 'country_code' => 'GB'],
        ['name' => "St Bernard's Catholic Grammar School", 'country_code' => 'GB'],
        ['name' => "Sutton Grammar School", 'country_code' => 'GB'],
        ['name' => "Sir Henry Floyd Grammar School", 'country_code' => 'GB'],
        ['name' => "Sir William Borlase's Grammar School", 'country_code' => 'GB'],
        ['name' => "Royal Grammar School", 'country_code' => 'GB'],
        ['name' => "Royal Latin School", 'country_code' => 'GB'],
        ['name' => "Tiffin School", 'country_code' => 'GB'],
        ['name' => "Tiffin Girls' School", 'country_code' => 'GB'],
        ['name' => "Upton Court Grammar School", 'country_code' => 'GB'],
        ['name' => "Wallington County Grammar School", 'country_code' => 'GB'],
        ['name' => "Wallington High School for Girls", 'country_code' => 'GB'],
        ['name' => "Watford Grammar School for Girls", 'country_code' => 'GB'],
        ['name' => "Wilson's School", 'country_code' => 'GB'],
        ['name' => "Channing School", 'country_code' => 'GB'],
        ['name' => "City of London School", 'country_code' => 'GB'],
        ['name' => "City of London School for Girls", 'country_code' => 'GB'],
        ['name' => "Emanuel School", 'country_code' => 'GB'],
        ['name' => "Epsom College", 'country_code' => 'GB'],
        ['name' => "Francis Holland School (Sloane Square)", 'country_code' => 'GB'],
        ['name' => "Francis Holland School (Regent's Park)", 'country_code' => 'GB'],
        ['name' => "Godolphin and Latymer School", 'country_code' => 'GB'],
        ['name' => "Hampton School", 'country_code' => 'GB'],
        ['name' => "Ibstock Place", 'country_code' => 'GB'],
        ['name' => "King's College School (Wimbledon)", 'country_code' => 'GB'],
        ['name' => "Kingston Grammar School", 'country_code' => 'GB'],
        ['name' => "Lady Eleanor Holles", 'country_code' => 'GB'],
        ['name' => "Latymer Upper School", 'country_code' => 'GB'],
        ['name' => "Merchant Taylors' School", 'country_code' => 'GB'],
        ['name' => "More House School", 'country_code' => 'GB'],
        ['name' => "North London Collegiate School", 'country_code' => 'GB'],
        ['name' => "Northwood College for Girls", 'country_code' => 'GB'],
        ['name' => "Notting Hill and Ealing High School", 'country_code' => 'GB'],
        ['name' => "Putney High School", 'country_code' => 'GB'],
        ['name' => "Queen's College London", 'country_code' => 'GB'],
        ['name' => "Queen's Gate School", 'country_code' => 'GB'],
        ['name' => "South Hampstead High School", 'country_code' => 'GB'],
        ['name' => "St Augustine's Priory", 'country_code' => 'GB'],
        ['name' => "St Benedict's School", 'country_code' => 'GB'],
        ['name' => "St Catherine's School", 'country_code' => 'GB'],
        ['name' => "St Helen's School", 'country_code' => 'GB'],
        ['name' => "St James Senior Boys' School", 'country_code' => 'GB'],
        ['name' => "St James Senior Girls' School", 'country_code' => 'GB'],
        ['name' => "St Margaret's School", 'country_code' => 'GB'],
        ['name' => "St Paul's Juniors", 'country_code' => 'GB'],
        ['name' => "St Paul's Girls' School", 'country_code' => 'GB'],
        ['name' => "Surbiton High School", 'country_code' => 'GB'],
        ['name' => "Sutton High School", 'country_code' => 'GB'],
        ['name' => "Westminster Under School", 'country_code' => 'GB'],
        ['name' => "Wimbledon High School", 'country_code' => 'GB'],
        ['name' => "Wycombe Abbey", 'country_code' => 'GB'],
        // Dubai Schools
        ['name' => "Dubai British School", 'country_code' => 'DU'],
        ['name' => "Dubai College", 'country_code' => 'DU'],
        ['name' => "Jumeirah English Speaking School", 'country_code' => 'DU'],
        ['name' => "King's School Dubai", 'country_code' => 'DU'],
        ['name' => "Repton School Dubai", 'country_code' => 'DU'],
        ['name' => "Dubai English Speaking School", 'country_code' => 'DU'],
        ['name' => "GEMS Wellington Academy", 'country_code' => 'DU'],
        ['name' => "GEMS Wellington International School", 'country_code' => 'DU'],
        ['name' => "Jumeirah College", 'country_code' => 'DU'],
        ['name' => "Nord Anglia International School Dubai", 'country_code' => 'DU'],
        ['name' => "Dubai International Academy", 'country_code' => 'DU'],
        ['name' => "GEMS Modern Academy", 'country_code' => 'DU'],
        ['name' => "Raffles World Academy", 'country_code' => 'DU'],
        ['name' => "Sunmarke School", 'country_code' => 'DU'],
        ['name' => "Dubai British School Emirates Hills", 'country_code' => 'DU'],
    ],
    'mock_exam_formats' => [
        'ANY' => 'any',
        'ONLINE' => 'online',
        'DOWNLOAD' => 'download',
        'PHYSICAL' => 'physical',
    ],
    'mock_exam_purchase_status' => [
        'NOT_STARTED' => 1,
        'IN_PROGRESS' => 2,
        'COMPLETED' => 3,
    ],
    'formats' => [
        'ANY' => 'any',
        'ONLINE' => 'online',
        'DOWNLOAD' => 'download',
        'PHYSICAL' => 'physical',
    ],
    'stripe_payment_status' => [
        'PENDING' => 'pending',
        'PAID' => 'paid',
        'FAILED' => 'failed',
        'CANCELLED' => 'canceled',
        'EXPIRED' => 'expired',
        'REFUNDED' => 'refunded',
        'PARTIALLY_REFUNDED' => 'partially_refunded',
    ],
    'active_status' => 'active',
    'announcement_status' => [
        'draft' => 0,
        'publish' => 1,
    ],
    'module_status' => [
        'inactive' => 0,
        'active' => 1,
    ],
];
